### ISSUE TITLE
Needs a library import...

### ISSUE THREAD

**Issue by canardleteer** [meereeum/glitchy#1]
This doesn't warrant a pull request, but:

import os

Needs to be added to the includes for it to work for me on Debian 7.9.

I love graphics projects like this!

**Comment by meereeum** [comment]
Thanks -- fixed.

Glad to hear you're enjoying and check back for updates - this is a WIP. Post if you generate anything interesting, too!

**Comment by canardleteer** [comment]
Projects like this are always WIPs, almost by definition.

But the ideological foundation of the project almost warrants a GIMP plugin.
